@startuml

actor Bibliotecario

participant "PrestitiView" as View
participant "ControllerPrestiti" as Controller
participant "ArchivioPrestiti" as Archivio
participant Prestito
participant Libro

Bibliotecario -> View: Apre schermata "Prestiti"
activate View
View --> Bibliotecario: 
Bibliotecario -> View: Seleziona "Ricerca Prestiti Attivi"
View --> Bibliotecario: 
Bibliotecario -> View: Compila form\ne clicca "Conferma"

View -> Controller: Invia i dati
deactivate View

activate Controller
Controller -> Controller: Valida\ni dati
alt Dati non validi
    Controller -> View: Mostra errore
    activate View
    View -> Bibliotecario: Messaggio di errore
    deactivate View
else Dati validi
    Controller -> Archivio: cercaPrestitiAttivi()
    activate Archivio
    Archivio --> Controller:
    deactivate Archivio
    alt Nessun prestito attivo trovato
        Controller -> View: Mostra errore
        activate View
        View -> Bibliotecario: Messaggio di errore
        deactivate View
    else Prestiti attivi trovati
        Controller --> View: Mostra prestito corrispondente
        activate View
        View -> Bibliotecario: Prestito corrispondente
        Bibliotecario -> View: Seleziona prestito \ne clicca "Chiudi"
        View -> Controller: Invia richiesta
        deactivate View
        Controller -> Archivio: registraRestituzione()
        activate Archivio
        Archivio --> Controller:
        Archivio -> Prestito: isRestituito()
        activate Prestito
        Prestito --> Archivio:
        deactivate Prestito
        Archivio -> Libro: incrementaCopie()
        activate Libro
        Libro -->  Archivio:
        deactivate Libro
        Archivio -> Studente: setPrestitiAttivi()
        activate Studente
        Studente --> Archivio:
        deactivate Studente
        deactivate Archivio
    end
end

@enduml